spring:
  application:
    name: Bank_REST_Test_Task
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: user
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
jasypt:
  encryptor:
    password: "${SECRET_CARD_NUMBER_KEY}"
    algorithm: PBEWITHHMACSHA512ANDAES_256
payment:
  card:
    tokenization:
      hash-key: "${HASH_SECRET_KEY}"